s_expr      = "(" s_expr_body ")"   | "(" ")"

s_expr_body = may_evals alls | may_evals
	(* т.к. с number начинаться нельзя! Это же не ф-ця которую можно эвалуировать. *)

alls           = all alls | all
all            = may_evals | may_not_evals
may_evals      = name | s_expr
may_not_evals  = number | spaces

(* -------- *)

name   = letter | letter name
letter = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
                  | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
                  | "u" | "v" | "w" | "x" | "y" | "z"

number = digit | digit number
digit  = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "0"

spaces = space | space spaces
space  = " " | "\n" | "\t"

	
(* "33ss" - тут (пока) это валидный код, с number и name. *)
